import type { Line } from "../../types";

import { blankLine } from "../blank-line";

export const block: Line[] = [
  {
    type: "p",
    segments: [
      { text: "████", className: "ansi-fg-0" },
      { text: "████", className: "ansi-fg-8" },
      { text: " " },
      { text: "████", className: "ansi-fg-1" },
      { text: "████", className: "ansi-fg-9" },
      { text: " " },
      { text: "████", className: "ansi-fg-2" },
      { text: "████", className: "ansi-fg-10" },
      { text: " " },
      { text: "████", className: "ansi-fg-3" },
      { text: "████", className: "ansi-fg-11" },
      { text: " " },
      { text: "████", className: "ansi-fg-4" },
      { text: "████", className: "ansi-fg-12" },
      { text: " " },
      { text: "████", className: "ansi-fg-5" },
      { text: "████", className: "ansi-fg-13" },
      { text: " " },
      { text: "████", className: "ansi-fg-6" },
      { text: "████", className: "ansi-fg-14" },
      { text: " " },
      { text: "████", className: "ansi-fg-7" },
      { text: "████", className: "ansi-fg-15" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: "████", className: "ansi-fg-0" },
      { text: "████", className: "ansi-fg-8" },
      { text: " " },
      { text: "████", className: "ansi-fg-1" },
      { text: "████", className: "ansi-fg-9" },
      { text: " " },
      { text: "████", className: "ansi-fg-2" },
      { text: "████", className: "ansi-fg-10" },
      { text: " " },
      { text: "████", className: "ansi-fg-3" },
      { text: "████", className: "ansi-fg-11" },
      { text: " " },
      { text: "████", className: "ansi-fg-4" },
      { text: "████", className: "ansi-fg-12" },
      { text: " " },
      { text: "████", className: "ansi-fg-5" },
      { text: "████", className: "ansi-fg-13" },
      { text: " " },
      { text: "████", className: "ansi-fg-6" },
      { text: "████", className: "ansi-fg-14" },
      { text: " " },
      { text: "████", className: "ansi-fg-7" },
      { text: "████", className: "ansi-fg-15" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: "████", className: "ansi-fg-0" },
      { text: "████", className: "ansi-fg-8" },
      { text: " " },
      { text: "████", className: "ansi-fg-1" },
      { text: "████", className: "ansi-fg-9" },
      { text: " " },
      { text: "████", className: "ansi-fg-2" },
      { text: "████", className: "ansi-fg-10" },
      { text: " " },
      { text: "████", className: "ansi-fg-3" },
      { text: "████", className: "ansi-fg-11" },
      { text: " " },
      { text: "████", className: "ansi-fg-4" },
      { text: "████", className: "ansi-fg-12" },
      { text: " " },
      { text: "████", className: "ansi-fg-5" },
      { text: "████", className: "ansi-fg-13" },
      { text: " " },
      { text: "████", className: "ansi-fg-6" },
      { text: "████", className: "ansi-fg-14" },
      { text: " " },
      { text: "████", className: "ansi-fg-7" },
      { text: "████", className: "ansi-fg-15" },
    ],
  },
  blankLine,
  blankLine,
  {
    type: "p",
    segments: [
      { text: "11111111", className: "ansi-fg-0" },
      { text: " " },
      { text: "22222222", className: "ansi-fg-1" },
      { text: " " },
      { text: "33333333", className: "ansi-fg-2" },
      { text: " " },
      { text: "44444444", className: "ansi-fg-3" },
      { text: " " },
      { text: "55555555", className: "ansi-fg-4" },
      { text: " " },
      { text: "66666666", className: "ansi-fg-5" },
      { text: " " },
      { text: "77777777", className: "ansi-fg-6" },
      { text: " " },
      { text: "88888888", className: "ansi-fg-7" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: "11111111", className: "ansi-fg-8" },
      { text: " " },
      { text: "22222222", className: "ansi-fg-9" },
      { text: " " },
      { text: "33333333", className: "ansi-fg-10" },
      { text: " " },
      { text: "44444444", className: "ansi-fg-11" },
      { text: " " },
      { text: "55555555", className: "ansi-fg-12" },
      { text: " " },
      { text: "66666666", className: "ansi-fg-13" },
      { text: " " },
      { text: "77777777", className: "ansi-fg-14" },
      { text: " " },
      { text: "88888888", className: "ansi-fg-15" },
    ],
  },
];
