import type { Line } from "../../types";

export const fade: Line[] = [
  {
    type: "p",
    segments: [
      { text: " " },
      { text: "▒▒▒▒", className: "ansi-fg-1" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-1" },
      { text: "   " },
      { text: "▒▒▒▒", className: "ansi-fg-2" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-2" },
      { text: "   " },
      { text: "▒▒▒▒", className: "ansi-fg-3" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-3" },
      { text: "   " },
      { text: "▒▒▒▒", className: "ansi-fg-4" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-4" },
      { text: "   " },
      { text: "▒▒▒▒", className: "ansi-fg-5" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-5" },
      { text: "   " },
      { text: "▒▒▒▒", className: "ansi-fg-6" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-14" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: " " },
      { text: "▒▒ ■", className: "ansi-fg-1" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-1" },
      { text: "   " },
      { text: "▒▒ ■", className: "ansi-fg-2" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-2" },
      { text: "   " },
      { text: "▒▒ ■", className: "ansi-fg-3" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-3" },
      { text: "   " },
      { text: "▒▒ ■", className: "ansi-fg-4" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-4" },
      { text: "   " },
      { text: "▒▒ ■", className: "ansi-fg-5" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-5" },
      { text: "   " },
      { text: "▒▒ ■", className: "ansi-fg-6" },
      { text: " " },
      { text: "▒▒", className: "ansi-fg-14" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: " " },
      { text: "▒▒ ", className: "ansi-fg-1" },
      { text: "▒▒▒▒", className: "ansi-fg-1" },
      { text: "   " },
      { text: "▒▒ ", className: "ansi-fg-2" },
      { text: "▒▒▒▒", className: "ansi-fg-2" },
      { text: "   " },
      { text: "▒▒ ", className: "ansi-fg-3" },
      { text: "▒▒▒▒", className: "ansi-fg-3" },
      { text: "   " },
      { text: "▒▒ ", className: "ansi-fg-4" },
      { text: "▒▒▒▒", className: "ansi-fg-4" },
      { text: "   " },
      { text: "▒▒ ", className: "ansi-fg-5" },
      { text: "▒▒▒▒", className: "ansi-fg-5" },
      { text: "   " },
      { text: "▒▒ ", className: "ansi-fg-6" },
      { text: "▒▒▒▒", className: "ansi-fg-14" },
    ],
  },
];
