import type { Line } from "../../types";

import { blankLine } from "../blank-line";

export const mouseface: Line[] = [
  {
    type: "p",
    segments: [
      { text: " █   █ ", className: "ansi-fg-9" },
      { text: " " },
      { text: "█   █ ", className: "ansi-fg-10" },
      { text: " " },
      { text: "█   █ ", className: "ansi-fg-11" },
      { text: " " },
      { text: "█   █ ", className: "ansi-fg-12" },
      { text: " " },
      { text: "█   █ ", className: "ansi-fg-13" },
      { text: " " },
      { text: "█   █ ", className: "ansi-fg-14" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: "  ■ ■  ", className: "ansi-fg-9" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-10" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-11" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-12" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-13" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-14" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: "  =■=  ", className: "ansi-fg-9" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-10" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-11" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-12" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-13" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-14" },
    ],
  },
  blankLine,
  {
    type: "p",
    segments: [
      { text: " █=@=█ ", className: "ansi-fg-1" },
      { text: " " },
      { text: "█=@=█ ", className: "ansi-fg-2" },
      { text: " " },
      { text: "█=@=█ ", className: "ansi-fg-3" },
      { text: " " },
      { text: "█=@=█ ", className: "ansi-fg-4" },
      { text: " " },
      { text: "█=@=█ ", className: "ansi-fg-5" },
      { text: " " },
      { text: "█=@=█ ", className: "ansi-fg-6" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: "  ■ ■  ", className: "ansi-fg-1" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-2" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-3" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-4" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-5" },
      { text: " " },
      { text: " ■ ■  ", className: "ansi-fg-6" },
    ],
  },
  {
    type: "p",
    segments: [
      { text: "  =■=  ", className: "ansi-fg-1" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-2" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-3" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-4" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-5" },
      { text: " " },
      { text: " =■=  ", className: "ansi-fg-6" },
    ],
  },
];
